### ISSUE TITLE
服务器端接受不到信息

### ISSUE THREAD

**Issue by se77en** [NetEase/pomelo-androidclient#2]
您好，我服务器端是用nodejs+socket.io写的，监听一个news事件，
socket.on('news', function (data) {
    //do something
});
android端用client.inform(route, msg);发送信息,route填什么呢？我一开始填的"/"后来换成是"news"，结果什么也收不到.
调试程序在Protocol.java return bt2Str(arr, 0, arr.length) + str;处返回 ������127.0.0.1:3000/{"timestamp":1364291264340,"news":"Hello Server,I am Android"}

前面这些������是什么？

**Comment by wensonsmith** [comment]
哥们，你解决了么，我要是碰见这个 ������

**Comment by py8765** [comment]
这个是包前面的route长度等消息，是正常的。
